version: '3.7'

services:
  nginx:
    build:
      context: ./back/docker/nginx
      dockerfile: Dockerfile-dev
    ports:
      - 80:80
    restart: always

  back:
    env_file: .env
    image: back
    build:
      context: ./back
      dockerfile: docker/back/Dockerfile-dev
    command: "poetry run flask run --host=0.0.0.0 --port ${APP_PORT}"
    volumes:
      - "./back:/home/app/back"
    ports:
      - 5000:5000
    # Read https://docs.docker.com/compose/startup-order/
    depends_on:
      - db
      - nginx

  front:
    env_file: .env
    build:
      context: ./front
      dockerfile: docker/Dockerfile-dev
    ports:
      - 3000:3000
    volumes:
      - "./front:/usr/src/app"
      - "container_node_modules:/usr/src/app/node_modules"
    depends_on:
      - nginx

  db:
    env_file: .env
    image: postgres:10.6-alpine

volumes:
  container_node_modules: