// FETCHING BACK API DATA
// --> CATEGORIES
export const ALL_CATEGORIES_FETCH_REQUESTED = "ALL_CATEGORIES_FETCH_REQUESTED"
export const ALL_CATEGORIES_FETCH_SUCCESS = "ALL_CATEGORIES_FETCH_SUCCESS"
export const ALL_CATEGORIES_FETCH_FAILED = "ALL_CATEGORIES_FETCH_FAILED"

// --> FOLDERS
export const FOLDER_FETCH_REQUESTED = "FOLDER_FETCH_REQUESTED"
export const FOLDER_FETCH_SUCCESS = "FOLDER_FETCH_SUCCESS"
export const FOLDER_FETCH_FAILED = "FOLDER_FETCH_FAILED"
export const GENERATE_FOLDER_TOCS = "GENERATE_FOLDER_TOCS"

// --> NOTES
export const NOTE_FETCH_REQUESTED = "NOTE_FETCH_REQUESTED"
export const NOTE_FETCH_SUCCESS = "NOTE_FETCH_SUCCESS"
export const NOTE_FETCH_FAILED = "NOTE_FETCH_FAILED"
export const REMOVE_NOTE_BODY = "REMOVE_NOTE_BODY"
export const GENERATE_NOTE_TOC_REQUESTED = "GENERATE_NOTE_TOC_REQUESTED"
export const GENERATE_NOTE_TOC_SUCCESS = "GENERATE_NOTE_TOC_SUCCESS"
export const GENERATE_NOTE_TOC_FAILED = "GENERATE_NOTE_TOC_FAILED"

// --> GENERIC ADD ENTITIES
export const ADD_ENTITIES = "ADD_ENTITIES"

// COMMON
export const STATUS = {REQUESTING: "REQUESTING", SUCCESS: "SUCCESS", FAILED: "FAILED"}